name: camel
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  sqlcool: ^3.2.1
  flutter:
    sdk: flutter
  fancy_bottom_navigation: ^0.3.2
  carousel_slider: ^1.3.0
  image_picker: ^0.6.1+4
  url_launcher: ^5.1.2
  badges: ^0.0.6
  http: ^0.12.0+1
  flutter_cupertino_date_picker: ^1.0.11
  toast: ^0.1.5
  flutter_open_whatsapp: ^0.1.2
  clipboard_manager: ^0.0.1
  wc_flutter_share: ^0.1.1
  firebase_messaging: ^5.1.2
  firebase_core: ^0.4.0+8
  firebase_database: ^3.0.5



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  like_button: ^0.1.7
  intl_translation: ^0.17.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/splash.png
    - images/man.png
    - images/home_drawer.png
    - images/sharr.png
    - images/home_bottom.png
    - images/about.png
    - images/log_out.png
    - images/contact.png
    - images/location.png
    - images/info.png
    - images/shopping_cart.png
    - images/cheap.png
    - images/share.png
    - images/twitter.png
    - images/youtube.png
    - images/telephone.png
    - images/instagram.png
    - images/snap.png
    - images/snapshat.png
    - images/logo.png
    - images/message.png
    - images/1.png
    - images/2.png
    - images/3.png
    - images/lab1.png
    - images/lab2.png
    - images/ready1.png
    - images/ready2.png
    - images/category.png
    - images/camel.png
    - images/caro1.png
    - images/caro2.png
    - images/caro3.png
    - images/cheap1.png
    - images/hashy.png
    - images/image.png
    - images/11.png
    - images/12.png
    - images/13.png
    - images/14.png
    - images/hwar.png
    - images/mafrood.png
    - images/meat.png
    - images/bell.png
    - images/home_pic.png
    - images/cart.png
    - images/driver.png
    - images/picture.png
    - images/add_photo.png
    - images/delete.png
    - images/edit.png
    - images/driver_pic.png
    - images/whats.png
    - images/add_driver_photo.png
    - images/ring.png
    - images/whatsapp.png
    - images/dollar_sign.png
    - images/man_order.png
    - images/sheep_order.png
    - images/time.png
    - images/order_photo.png
    - images/float.png
    - images/call-answer.png
    - images/sent-mail.png
    - images/snap_section1.png
    - images/snap_sectioon2.png
    - images/lpany.png
    - images/good_code.png
    - images/coin.png
    - images/Success.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family:  black75
      fonts:
        - asset: fonts/FrutigerLTArabic-75Black.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: bold65
      fonts:
         - asset: fonts/FrutigerLTArabic-65Bold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
